name: run pull request CI

on:
  schedule:
    - cron:  '0 12 * * *'  # daily ~8am est
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: "ubuntu-20.04"  # see: https://github.com/actions/setup-python/issues/544
    timeout-minutes: 10
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9, "3.10", "3.11"]
        command: ["py", "scaffolds", "sqlalchemy-1.4", "sqlalchemy-2"]
        exclude:
          # SQLAlchemy2 requires >= py3.7
          - python: 3.6
            command: "sqlalchemy-2"

    steps:
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install tox
        run: pip install tox
      - name: run tox unit tests
        run: tox -e ${{ matrix.command }}
