name: run pull request CI

on:
  schedule:
    - cron:  '0 12 * * *'  # daily ~8am est
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10
    strategy:
      matrix:
        python: [3.8, 3.9, "3.10", "3.11", "3.12", "3.13"]
        command: ["py", "scaffolds", "sqlalchemy-1.4", "sqlalchemy-2"]

    steps:
      - uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: install tox
        run: pip install tox
      - name: run tox unit tests
        run: tox -e ${{ matrix.command }}
